# Generated by Django 4.1.7 on 2023-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email_2', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
