# Generated by Django 4.1.7 on 2023-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('name', models.TextField(max_length=100)),
                ('price', models.TextField(max_length=100)),
            ],
        ),
    ]
