# Generated by Django 4.1.7 on 2023-05-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_item_add_image1_item_add_image2_item_add_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='modal_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id_item',
            field=models.TextField(default='default_id_popup', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='id_popup',
            field=models.TextField(default='default_id_popup', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='default_description', max_length=500),
        ),
    ]
