# Generated by Django 4.1.7 on 2023-05-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_item_item_id_remove_item_modal_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
