# Generated by Django 4.1.7 on 2023-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('add_image1', models.TextField(default='default_value')),
                ('add_image2', models.TextField(default='default_value')),
                ('add_image3', models.TextField(default='default_value')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(default='default_description', max_length=500)),
                ('price', models.TextField(max_length=100)),
                ('id_popup', models.TextField(default='default_id_popup', max_length=100)),
                ('id_item', models.TextField(default='default_id_popup', max_length=100)),
            ],
        ),
    ]
